name: mockito_test
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mockito: ^5.0.10

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.0.5
